# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [1]:
# import libraries
import numpy as np 
import pandas as pd

In [2]:
# load messages dataset
messages = pd.read_csv('messages.csv')
messages.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [3]:
messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26248 entries, 0 to 26247
Data columns (total 4 columns):
id          26248 non-null int64
message     26248 non-null object
original    10184 non-null object
genre       26248 non-null object
dtypes: int64(1), object(3)
memory usage: 820.3+ KB

In [4]:
# load categories dataset
categories = pd.read_csv('categories.csv')
categories.head()

   id                                         categories
0   2  related-1;request-0;offer-0;aid_related-0;medi...
1   7  related-1;request-0;offer-0;aid_related-1;medi...
2   8  related-1;request-0;offer-0;aid_related-0;medi...
3   9  related-1;request-1;offer-0;aid_related-1;medi...
4  12  related-1;request-0;offer-0;aid_related-0;medi...

In [5]:
categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26248 entries, 0 to 26247
Data columns (total 2 columns):
id            26248 non-null int64
categories    26248 non-null object
dtypes: int64(1), object(1)
memory usage: 410.2+ KB

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [6]:
# merge datasets
df = messages.merge(categories, on=('id'))
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26386 entries, 0 to 26385
Data columns (total 5 columns):
id            26386 non-null int64
message       26386 non-null object
original      10246 non-null object
genre         26386 non-null object
categories    26386 non-null object
dtypes: int64(1), object(4)
memory usage: 1.2+ MB

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [8]:
# create a dataframe of the 36 individual category columns
categories = df['categories'].str.split(';', expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [9]:
# select the first row of the categories dataframe
row = categories.loc[0]

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = (row.apply(lambda x: x[:-2])).tolist()
print(category_colnames)

['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']

In [10]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [11]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].astype(str).str[-1]
    
    # convert column from string to numeric
    categories[column] = categories[column].astype(int)
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [12]:
# drop the original categories column from `df`
df.drop(['categories'], axis = 1, inplace=True)
df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [13]:
# concatenate the original dataframe with the new `categories` dataframe
df = pd.concat([df, categories], axis=1, join='inner')
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26386 entries, 0 to 26385
Data columns (total 40 columns):
id                        26386 non-null int64
message                   26386 non-null object
original                  10246 non-null object
genre                     26386 non-null object
related                   26386 non-null int64
request                   26386 non-null int64
offer                     26386 non-null int64
aid_related               26386 non-null int64
medical_help              26386 non-null int64
medical_products          26386 non-null int64
search_and_rescue         26386 non-null int64
security                  26386 non-null int64
military                  26386 non-null int64
child_alone               26386 non-null int64
water                     26386 non-null int64
food                      26386 non-null int64
shelter                   26386 non-null int64
clothing                  26386 non-null int64
money                     26386 non-null int64
missing_people            26386 non-null int64
refugees                  26386 non-null int64
death                     26386 non-null int64
other_aid                 26386 non-null int64
infrastructure_related    26386 non-null int64
transport                 26386 non-null int64
buildings                 26386 non-null int64
electricity               26386 non-null int64
tools                     26386 non-null int64
hospitals                 26386 non-null int64
shops                     26386 non-null int64
aid_centers               26386 non-null int64
other_infrastructure      26386 non-null int64
weather_related           26386 non-null int64
floods                    26386 non-null int64
storm                     26386 non-null int64
fire                      26386 non-null int64
earthquake                26386 non-null int64
cold                      26386 non-null int64
other_weather             26386 non-null int64
direct_report             26386 non-null int64
dtypes: int64(37), object(3)
memory usage: 9.5+ MB

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [15]:
# check number of duplicates
duplicates = df.duplicated()
duplicates.sum()

170

In [16]:
df[duplicates]

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
164,202,?? port au prince ?? and food. they need gover...,p bay pap la syen ak manje. Yo bezwen ed gouve...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
165,202,?? port au prince ?? and food. they need gover...,p bay pap la syen ak manje. Yo bezwen ed gouve...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
658,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
659,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
660,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
715,862,What is the address of the radio station? I as...,Ki adres radyo a? Paske m bezwen al depoze dos...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
716,862,What is the address of the radio station? I as...,Ki adres radyo a? Paske m bezwen al depoze dos...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1415,1652,"please we need water, food and tents, we have ...","p jwen dlo, manje, tant pou nou demi nou gen 1...",direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1416,1652,"please we need water, food and tents, we have ...","p jwen dlo, manje, tant pou nou demi nou gen 1...",direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2139,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2140,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2141,2446,How much money did TV Latino American collect ...,Konbyen kob tv latino america ranmase miami,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2803,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2804,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2805,3217,"Sir or madam, I'm hungry, I cannot stand becau...",Mesye ou madam mwen grangou mwen pa menm kakan...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2838,3250,I thought you gave my number and this was seri...,Mwen tepanse le nou tebay nimewo a se yon afse...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2839,3250,I thought you gave my number and this was seri...,Mwen tepanse le nou tebay nimewo a se yon afse...,direct,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3389,3882,"I am in Carefour Feuilles, Dkayet neighborhood...",Mwen nan kafou fy zon dekayt nou beswen dlo po...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3390,3882,"I am in Carefour Feuilles, Dkayet neighborhood...",Mwen nan kafou fy zon dekayt nou beswen dlo po...,direct,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
3868,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3869,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3870,4412,"Good evening staff of responsibles, please giv...",Bonswa staf responsab svp banm yon ti d paske ...,direct,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4360,4956,"What we saw yesterday is a sign, you need to k...",a nou w la yo se sign yoy ou bezwen kon sa Jez...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4361,4956,"What we saw yesterday is a sign, you need to k...",a nou w la yo se sign yoy ou bezwen kon sa Jez...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4543,5153,there are people in Delmas 32 who form an asso...,Ginyin yon paket moun delmas 32 ki forme organ...,direct,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4544,5153,there are people in Delmas 32 who form an asso...,Ginyin yon paket moun delmas 32 ki forme organ...,direct,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4652,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4653,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4654,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4917,5573,"If I would like to find a job in cepoz, what s...",Si mwen ta renmen jwen travay nan cepoz ki sa ...,direct,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20073,23229,* German Agro Action (GAA) reported that in th...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
20991,24247,"As we approach Luabo, I get my first impressio...",NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20992,24247,"As we approach Luabo, I get my first impressio...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
21083,24347,In response to North Korea's devastating artil...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
21084,24347,In response to North Korea's devastating artil...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
21477,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21478,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21479,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21480,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21481,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21482,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21483,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
21484,24779,Shelter materials (thick polyesters) are being...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
22153,25512,The flood situation has worsened with nearly 3...,NaN,news,1,0,0,1,0,0,...,0,1,1,1,0,0,0,0,0,0
22154,25512,The flood situation has worsened with nearly 3...,NaN,news,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,0,0
23736,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23737,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23738,27296,The regime says the charter will clear the way...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24169,27768,An EU-backed French offensive against rebels r...,NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24170,27768,An EU-backed French offensive against rebels r...,NaN,news,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24779,28462,"To date, a total of 39 people suffering from E...",NaN,news,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
24780,28462,"To date, a total of 39 people suffering from E...",NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
24988,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24989,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
24990,28687,"At present, UNHCR has 2,500 additional tents a...",NaN,news,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
25291,29022,"In a field in Jallouzai, just inside Pakistan,...",NaN,news,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
25292,29022,"In a field in Jallouzai, just inside Pakistan,...",NaN,news,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
25378,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25379,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
25380,29119,Most victims (90 per cent) show little or no s...,NaN,news,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# drop duplicates
df = df.drop_duplicates(keep='first')

In [18]:
# check number of duplicates
duplicates = df.duplicated()
duplicates.sum()

0

In [19]:
#Let´s investigate our dataset:
df.nunique()

id                        26180
message                   26177
original                   9630
genre                         3
related                       3
request                       2
offer                         2
aid_related                   2
medical_help                  2
medical_products              2
search_and_rescue             2
security                      2
military                      2
child_alone                   1
water                         2
food                          2
shelter                       2
clothing                      2
money                         2
missing_people                2
refugees                      2
death                         2
other_aid                     2
infrastructure_related        2
transport                     2
buildings                     2
electricity                   2
tools                         2
hospitals                     2
shops                         2
aid_centers                   2
other_infrastructure          2
weather_related               2
floods                        2
storm                         2
fire                          2
earthquake                    2
cold                          2
other_weather                 2
direct_report                 2
dtype: int64

Based on the unique values, we can see that both the "related" and "child alone" variables do have different counts of unique values compared to the other categories. So let´s look into these closer.

In [20]:
df['related'].value_counts()

1    19906
0     6122
2      188
Name: related, dtype: int64

In [21]:
df[df['related'] == 2]

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
117,146,Dans la zone de Saint Etienne la route de Jacm...,Nan zon st. etine rout jakmel la bloke se mize...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221,263,. .. i with limited means. Certain patients co...,t avec des moyens limites. Certains patients v...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,373,The internet caf Net@le that's by the Dal road...,Cyber cafe net@le ki chita rout de dal tou pr ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
462,565,"Bonsoir, on est a bon repos aprs la compagnie ...",Bonswa nou nan bon repo apri teleko nan wout t...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
578,700,URGENT CRECHE ORPHANAGE KAY TOUT TIMOUN CROIX ...,r et Salon Furterer. mwen se yon Cosmtologue. ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
657,804,elle est vraiment malade et a besoin d'aide. u...,she is really sick she need your help. please ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
889,1063,no authority has passed by to see us. We don't...,EN OKENN OTORITE POKO PASE WE NOU NOU PAGEN KO...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
903,1080,It's Over in Gressier. The population in the a...,Se over toujou nan gresye 24e seksyon komin. P...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
931,1113,we sleep with the baby. Thanks in advance for ...,sa nou demi avek ti bebe. Mesi davans pou d no...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
937,1121,I need help in Jrmie because I was in Port-au-...,MWEN bezwen ed lan jeremi paske mwen te portop...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
939,1123,fsa pou mwen s v p map mouri mwen gen tout po ...,f la kise moniquk fasa pou mwen s v p map mour...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1234,1460,".. Gonaives, in a place called Canal Bois in F...",ou GONAVE NAN YON zon ki se kanal bwa m ekri m...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1256,1483,GEN YON TIBEBE KI MALAD NAN KOU PASKE BLOK TON...,VIRE NAN BO KKOTI YZIN NAN. WAP JWENN YON KAFO...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1317,1550,don't understand the first part. .. understand...,zwen e koman demache la ye. mesi pou konprehan...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1409,1648,Est-ce que ya monde qui aller U. s. a et qui o...,Eske yon mounn ka ale usa ak yon timoun ki ame...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1506,1747,Gens ont information qui dit que si on moins c...,GEN YON ENFOMASYON KI DI SI YON MOUN SITWAYEN ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1694,1951,This is my address : Cersine 8 Prolong. .. .,. min adres mouin : cersine 8 prolonges,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1788,2051,I would like to have some information on the l...,MWEN TA RENMEN GEN KEK ENFOMASYON SOU DENYE KA...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2354,2696,No location : Ou se trouve l'ambassade du Snga...,OU SE TROUVE LAMBASSADE DU SENEGAL EN HAITI?,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2479,2840,Je veux savoir comment je peux obtenir de l'ai...,I want to know how i can get some support for ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2544,2920,"142, Ruelle Beaulieu, Mon Repos 44 Carrefour","142, ruelle beaulieu mon repos 44 carrefour",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2560,2936,". .. Esdras. Address : Solidarit Village, Tou...",UL ESDRAS ADRESSE VILLAGE SOLIDARITE RUE T LOU...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3033,3481,Route des dalles prolonges #277 after Morne Je...,route des dalles prolongue # 277 apres le morn...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3138,3603,we are in rue Dessalines Petit goaves and it n...,Nous sommes rue Dessalines ( petit-gouve ) et...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3374,3866,I am very happy to get the messages that tell ...,M byen kontan jwenn mesaj nou yo ki enfome m d...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3630,4145,mouin vle kite ayiti depi kek jou.,I want to leave haiti please for some days,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4609,5219,Mwen ta renmen jwenn yon djb. ske gen posiblit...,"I wannan found one jod, how like I can got it....",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4651,5265,(Delmas 33 Charboniere infomatyon s'il vous pl...,"Delmas 33, charbonniere, information please.",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4746,5367,Carrefour Feuille rue Mgr Prol # 39,CARREFOUR FEUILLE RUE MGR PROL #39,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4805,5437,Ede m nan lort pou genyen yon bourss,"i need your help please, in other to have a sc...",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12392,14593,SYED EJAZ BUKHARI MAOZA SHAH WALI TEHSIL ALI P...,SYED EJAZ BUKHARI MAOZA SHAH WALI TEHSIL ALI P...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12396,14598,TAUSEEF KHAN S/O AKBAR DIN MIANWALI TEH ESSA K...,TAUSEEF KALA / MANGLI VIA / ESS ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12397,14601,TAUSEEF KHAN S/O AKBAR DIN MIANWALI TEH ESSA K...,NAAM.TAUSEEF KHAN S/ AKBAR DIN. MIANWALI KIYA ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12398,14602,TEH SUHBAT PUR VILL NASEER KHAN KHOSA MY PRESE...,TEH SUHBAT PUR VILL NASEER KHAN KHOSA Mera Var...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12407,14613,UN aur UN K Nimaidon ko Apeel krt hain k? Hama...,! a,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12416,14632,I allhadino khaskheli UC chatto a dehe a shalu...,allhadino khaskheli chatto dehe a shalunka ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12418,14635,village koor mir mohmmad u c burira takuka kha...,"GAON: KOOR, MERA NAAM MOHAMMAD U C BURIRA TAKU...",direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12425,14643,gaav valay aahar aor aarthik samashyaa saamna ...,villagers r facing food and financial problm k...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12427,14645,"CONNFCTION / . SOLANGI, ...",CONNFCTION B / C . VILLAGE ...,direct,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12479,14720,@jujoffer: So Frankenstorm has been reduced to...,NaN,social,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12685,14980,#SandyUntappd ‚àö‚â• Drinking an Oatmeal Stout...,NaN,social,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12758,15073,atrickSF @antmarshall @kleankut1 @somarlavous ...,NaN,social,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13732,16248,"Les habitants, dont l'activité est essentielle...",NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14938,17564,"Jusqu'à présent, les 133 femmes qui participen...",NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15029,17668,Despite rapid deliveries of tents and other re...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15609,18290,All available resources were put forward to de...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15933,18650,The six countries will also adopt a training c...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15979,18705,"""It was very windy and there were heavy thunde...",NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16046,18777,The 50 international hospital staff lived in a...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16925,19747,L'Armée suisse a cependant le savoir-faire et ...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17528,20421,PETR V. ILIICHEV (Russian Federation) said the...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18381,21367,"* Par ailleurs, aucune victime française n'a é...",NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18644,21661,Refugees International therefore recommends that:,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19849,22985,This combination of low agricultural productio...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20192,23358,"crop, loss of hydro-electric generating capaci...",NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20465,23662,transferred to a sanitary landfill site by a,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20636,23861,Families also have solar lamps which can be re...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22481,25874,Read the [full blog post](http://www.odi.org.u...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23537,27071,Actualmente e independientemente de la ayuda d...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25385,29126,Mali's former President Amadou Toumani Touré -...,NaN,news,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df['child_alone'].value_counts()

0    26216
Name: child_alone, dtype: int64

For the variable "related" it seems that "2" could be a manual mistake. Let´s assume it is in fact the value "1"
for the variable "child_alone", we see that there are not input available. This variable can be dropped.

In [23]:
df['related'].replace(2, 1, inplace=True)
df.drop(['child_alone'], axis=1, inplace=True)
df.nunique()

id                        26180
message                   26177
original                   9630
genre                         3
related                       2
request                       2
offer                         2
aid_related                   2
medical_help                  2
medical_products              2
search_and_rescue             2
security                      2
military                      2
water                         2
food                          2
shelter                       2
clothing                      2
money                         2
missing_people                2
refugees                      2
death                         2
other_aid                     2
infrastructure_related        2
transport                     2
buildings                     2
electricity                   2
tools                         2
hospitals                     2
shops                         2
aid_centers                   2
other_infrastructure          2
weather_related               2
floods                        2
storm                         2
fire                          2
earthquake                    2
cold                          2
other_weather                 2
direct_report                 2
dtype: int64

In [24]:
df['related'].value_counts()

1    20094
0     6122
Name: related, dtype: int64

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [26]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///DisasterResponseProject.db')
df.to_sql('Message', engine, if_exists='replace', index=False)

### 8. Use this notebook to complete `process_data.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `process_data.py` in the classroom on the `Project Workspace IDE` coming later.